version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./html:/usr/share/nginx/html

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: flightbooking
      POSTGRES_USER: flightadmin
      POSTGRES_PASSWORD: flightpass
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
